### PR TITLE
xStorage Issue96 opticaldiskdriveletter

### PR DESCRIPTION
**Pull request by timhaintz**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

### CODE REVIEW

**Comment by kewalaka** [comment]
hi @timhaintz  I don't see any changes in the pull request - have you committed them?

**Comment by timhaintz** [comment]
Thanks for checking in @kewalaka , I seem to have gotten myself into a Git and GitHub knot. I'm a bit confused.
I cloned your latest repo into VSCode. 
Git Log shows the last modified date as Sun Dec 17 09:55:15 2017. I'm on the issue96-opticaldiskdriveletter branch. What I'm confused about is, I created this pull request, I don't know how to work on this in VSCode though. Do I just work on your branch and then Push to that? A GitHub Pull Request doesn't seem to have anything to do with Git in VSCode. 

I guess my question is, what is the GitHub workflow if I'm using VSCode? Do I just push and you see the changes and then I create a Pull Request to document that?

Hope that makes sense, the GitHub work flow part is confusing me.

Thanks, Tim.

**Comment by timhaintz** [comment]
Sorry, I see what I've done wrong (https://gist.github.com/Chaser324/ce0505fbed06b947d962). I opened the Pull Request before I made any changes. @kewalaka are you happy to leave this Pull Request open while I Fork it, make the changes and you can check the changes? Thanks, Tim.

**Comment by kewalaka** [comment]
Yes no hurry from my perspective, I'm on call over Christmas so not going
anywhere!

**Comment by timhaintz** [comment]
Thanks @kewalaka I was on call last year. Hope it is a quiet one for you this year, like mine last. Will get onto the updates tonight and in the morning. Thanks!

**Comment by timhaintz** [comment]
Closing this Pull Request off as I did it in the wrong order. I have now forked the repo and made the changes. Will create a new Pull Request and add my changes. https://github.com/timhaintz/xStorage/tree/issue96-opticaldiskdriveletter

**Pull request closed without merging**
