### PR TITLE
Issue 96 change driveletter cdrom

### PR DESCRIPTION
**Pull request by timhaintz**
Trying to help out if I can.

### CODE REVIEW

**Comment by timhaintz** [comment]
Bit confused about what I'm doing wrong, any help appreciated. When I  'git clone https://github.com/kewalaka/xStorage.git' the MSFT_xCDROM module doesn't appear. Am I cloning the wrong thing? In the web interface, I can see it. When I clone it or download the ZIP, the module doesn't appear. Thanks, Tim.

**Comment by timhaintz** [comment]
I was on the dev branch by default and couldn't see the correct branch by default. https://stackoverflow.com/questions/67699/how-to-clone-all-remote-branches-in-git helped me out.

**Comment by kewalaka** [comment]
hi @timhaintz - I've re-based the branch this morning currently working through the list of code review tasks

**Comment by kewalaka** [comment]
hi - closing this PR as it's now behind my latest patch

**Comment by timhaintz** [comment]
Thanks @kewalaka

**Pull request closed without merging**
